# Generated by Django 4.2.4 on 2023-08-11 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_doctors_dep_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='dep_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.about'),
        ),
    ]
