# Generated by Django 4.2.4 on 2023-08-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_booked_on_booking_booked_on_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Departments',
        ),
    ]
